sudo: required
services:
  - docker

before_install:
  - docker build -t aimer1319/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run aimer1319/multi-docker npm test -- --coverage

after_success:
  - docker build -t aimer1319/multi-client ./client 
  - docker build -t aimer1319/multi-nginx ./nginx
  - docker build -t aimer1319/multi-server ./server
  - docker build -t aimer1319/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push aimer1319/multi-client
  - docker push aimer1319/multi-nginx
  - docker push aimer1319/multi-server
  - docker push aimer1319/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-065478386807
  bucket_path: docker-multi
  on:
    branch:  master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    
